export const items = [
  {
    id: 0,
    label: "Ceyrek",
    type: "Ziynet",
    history: "Yeni",
    unit: "adet",
    weight: 1.754,
    has: 1.608,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 1,
    label: "Ceyrek",
    type: "Ziynet",
    history: "Eski",
    unit: "adet",
    weight: 1.754,
    has: 1.608,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 2,
    label: "Ceyrek",
    type: "Ata",
    history: "Yeni",
    unit: "adet",
    weight: 1.804,
    has: 1.654,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 3,
    label: "Ceyrek",
    type: "Ata",
    history: "Eski",
    unit: "adet",
    weight: 1.804,
    has: 1.654,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 4,
    label: "Yarim",
    type: "Ziynet",
    history: "Yeni",
    unit: "adet",
    weight: 3.508,
    has: 3.216,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 5,
    label: "Yarim",
    type: "Ziynet",
    history: "Eski",
    unit: "adet",
    weight: 3.508,
    has: 3.216,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 6,
    label: "Yarim",
    type: "Ata",
    history: "Yeni",
    unit: "adet",
    weight: 3.608,
    has: 3.307,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 7,
    label: "Yarim",
    type: "Ata",
    history: "Eski",
    unit: "adet",
    weight: 3.608,
    has: 3.307,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 8,
    label: "Tam",
    type: "Ziynet",
    history: "Yeni",
    unit: "adet",
    weight: 7.016,
    has: 6.431,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 9,
    label: "Tam",
    type: "Ziynet",
    history: "Eski",
    unit: "adet",
    weight: 7.016,
    has: 6.431,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 10,
    label: "Tam",
    type: "Ata",
    history: "Yeni",
    unit: "adet",
    weight: 7.216,
    has: 6.615,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 11,
    label: "Tam",
    type: "Ata",
    history: "Eski",
    unit: "adet",
    weight: 7.216,
    has: 6.615,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 12,
    type: "22",
    label: "Bilezik",
    setting: 22,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 13,
    type: "18",
    label: "Bilezik",
    setting: 18,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 14,
    type: "14",
    label: "Bilezik",
    setting: 14,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 15,
    type: "14",
    label: "Yuzuk",
    setting: 14,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 16,
    type: "18",
    label: "Yuzuk",
    setting: 18,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 17,
    type: "22",
    label: "Yuzuk",
    setting: 22,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 18,
    type: "14",
    label: "Kunye",
    setting: 14,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 19,
    type: "18",
    label: "Kunye",
    setting: 18,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 20,
    type: "22",
    label: "Kunye",
    setting: 22,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 21,
    type: "14",
    label: "Gerdanlik",
    setting: 14,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 22,
    type: "18",
    label: "Gerdanlik",
    setting: 18,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 23,
    type: "22",
    label: "Gerdanlik",
    setting: 22,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 24,
    type: "14",
    label: "Set",
    setting: 14,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },

  {
    id: 25,
    type: "18",
    label: "Set",
    setting: 18,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 26,
    type: "22",
    label: "Set",
    setting: 22,
    unit: "gr",
    has: 0,
    amount: "",
    workship: 100,
  },
  {
    id: 27,
    type: "Ziynet",
    label: "Gremse",
    unit: "adet",
    weight: 17.54,
    has: 16.078,
    amount: 1,
    setting: 22,
    workship: 100,
  },
  {
    id: 28,
    type: "Ata",
    label: "Gremse",
    unit: "adet",
    weight: 18.04,
    has: 16.537,
    amount: 1,
    setting: 22,
    workship: 0,
  },
  {
    id: 29,
    type: "Ziynet",
    label: "5'li",
    unit: "adet",
    weight: 35.08,
    has: 32.157,
    amount: 1,
    setting: 22,
    workship: 0,
  },
  {
    id: 30,
    type: "Ata",
    label: "5'li",
    unit: "adet",
    weight: 36.08,
    has: 33.073,
    amount: 1,
    setting: 22,
    workship: 0,
  },

  {
    id: 31,
    type: "24",
    label: "Gram A",
    unit: "adet",
    weight: 1,
    has: 1,
    setting: 24,
    amount: 1,
    workship: 0,
  },
  {
    id: 32,
    type: "Ata",
    label: "Gram A",
    unit: "adet",
    weight: 1,
    has: 0.917,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 33,
    type: "Ziynet",
    label: "Gram A",
    unit: "adet",
    weight: 1,
    has: 0.917,
    setting: 22,
    amount: 1,
    workship: 0,
  },
  {
    id: 34,
    type: "22",
    label: "Diger",
    unit: "gr",
    has: 0,
    setting: 22,
    amount: "",
    workship: 100,
  },
  {
    id: 35,
    type: "18",
    label: "Diger",
    unit: "gr",
    has: 0,
    setting: 18,
    amount: "",
    workship: 100,
  },
  {
    id: 36,
    type: "14",
    label: "Diger",
    unit: "gr",
    has: 0,
    setting: 14,
    amount: "",
    workship: 100,
  },
  {
    id: 37,
    type: "24",
    label: "Diger",
    unit: "gr",
    has: 0,
    setting: 24,
    amount: "",
    workship: 100,
  },
  {
    id: 38,
    type: "Saat",
    label: "Erkek",
    unit: "adet",
    has: 1,
    weight: 1,
    amount: 1,
    workship: 0,
  },
  {
    id: 39,
    type: "Saat",
    label: "Bayan",
    unit: "adet",
    has: 1,
    weight: 1,
    amount: 1,
    workship: 0,
  },
];
